services:
  asset-maintenance:
    build:
      args: 
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
      dockerfile: Dockerfile.asset_maintenance
    command: python -u AIOps_Asset_Maintenance.py
    environment: 
      - DATASET_DIR=${DATASET_DIR}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
    image: ${FINAL_IMAGE_NAME}:asset-maintenance-ubuntu-20.04
    privileged: true
    volumes: 
      - ${DATASET_DIR}:/dataset
      - $PWD:/workspace
    working_dir: /workspace/AIOps
